kind: Service
apiVersion: v1
metadata:
  namespace: {{.Release.Namespace}}
  name: hubble-ui
spec:
  selector:
    app: hubble-ui
  ports:
    - name: http
      port: 80
      targetPort: 8081
  type: ClusterIP
